### ISSUE TITLE
Cross origin error after node-jwks-rsa v1.8.0

### ISSUE THREAD

**Issue by loremaps** [Levino/mock-jwks#26]
Hi and thanks for this useful package!

Since <https://github.com/auth0/node-jwks-rsa/releases/v1.8.0> my jest test are failing with the following error:

```
   console.error
      Error: Cross origin http://localhost forbidden
          at dispatchError (/test/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:54:19)
          at Object.validCORSHeaders (/test/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:66:5)
          at receiveResponse (/test/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:843:21)
          at Request.<anonymous> (/test/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:678:38)
          at Request.emit (events.js:315:20)
          at Request.EventEmitter.emit (domain.js:547:15)
          at Request.onRequestResponse (/test/node_modules/request/request.js:1066:10)
          at OverriddenClientRequest.emit (events.js:315:20)
          at OverriddenClientRequest.EventEmitter.emit (domain.js:547:15)
          at respond (/test/jobtopus-graph-api/node_modules/nock/lib/playback_interceptor.js:299:11) undefined
```

Do you think this is an upstream issue?

**Comment by Levino** [comment]
Please either comment in #27 how to reproduce or create a PR with a failing test.

**Comment by Levino** [comment]
Also `node-jkws-rsa` is neither a direct nor indirect dependency of this project. As far as I can tell at least.

**Comment by Levino** [comment]
Okay, so the correct name of the package is [`jwks-rsa`](https://www.npmjs.com/package/jwks-rsa) which I used in version `1.8.0` in #27 without any issues. I guess your express server is misconfigured. and should send cors headers.

**Comment by loremaps** [comment]
OK, I have identified my issue! 

In release `1.8.0` of [jwks-rsa](https://github.com/auth0/node-jwks-rsa) the deprecated [request](https://github.com/request/request) is replaced with [axios](axios/axios).

I am using [jest](https://github.com/facebook/jest) and the `testEnvironment: 'node'` was not picked up correctly (my repo is a microservice monorepo)

You can see this on my stacktrace above where it says `jsdom` 🤦 

With  `testEnvironment: 'node'` set correctly, all works fine. So, thanks again for your time and this lib!
